### PR TITLE
More Fixes

### PR DESCRIPTION
**Pull request by dheap**
Think I've messed this one up as your branch must have been behind mine. 
Can you cherrypick just 7d8052d71f10c6daab96d6b8330f6d18518d157f from my branch?

### CODE REVIEW

**Comment by dheap** [comment]
I used this to create my rhwood-catala branch:
```
git checkout -b rhwood-catala master
git pull https://github.com/rhwood/JMRI.git catala

I must have done the wrong thing.
```

**Comment by rhwood** [comment]
Did you pull an update from JMRI/master?

(Do you have that triangular setup that we list on our website that always pulls updates from JMRI/master whenever pulling any branch)?

Randall Wood
JMRI Developer - http://jmri.org
Alexandria Software - http://alexandriasoftware.com
Northern Virginia NTRAK - http://nvntrak.org

**Comment by dheap** [comment]
> Did you pull an update from JMRI/master?

I didn't do  so explicitly.

> (Do you have that triangular setup that we list on our website that always pulls updates from JMRI/master whenever pulling any branch)?

Probably. I have this:
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = https://dheap@github.com/JMRI/JMRI.git
	fetch = +refs/heads/*:refs/remotes/origin/*
	pushurl = https://dheap@github.com/dheap/JMRI.git
[branch "master"]
	remote = origin
	merge = refs/heads/master
[branch "release-4.7.4"]
	remote = origin
	merge = refs/heads/release-4.7.4
[branch "release-4.7.5"]
	remote = origin
	merge = refs/heads/release-4.7.5
```
Not sure where those last two came from...

Is this the offending line?
`	fetch = +refs/heads/*:refs/remotes/origin/*
`

**Comment by dheap** [comment]
Bedtime here now...

**Comment by rhwood** [comment]
This is what I have for origin:
```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
        ignorecase = true
        precomposeunicode = true
[remote "origin"]
        url = https://github.com/rhwood/JMRI.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
... more branches ...
[remote "upstream"]
        url = https://github.com/JMRI/JMRI.git
        fetch = +refs/heads/*:refs/remotes/upstream/*
... more branches ...
[remote "dheap"]
        url = https://github.com/dheap/JMRI.git
        fetch = +refs/heads/*:refs/remotes/dheap/*
[branch "slot-monitor"]
        remote = origin
        merge = refs/heads/slot-monitor
```

These means that I have to do a manual pull from upstream/master when I want to update any of my branches to contain what's in the JMRI master branch, but that I am not always working from it as well.

**Comment by rhwood** [comment]
I think this got cherry picked into JMRI/master correctly, so closing.

**Pull request closed without merging**
